### ISSUE TITLE
execvp: ar: Argument list too long

### ISSUE THREAD

**Issue by psxdev** [ps4dev/ps4sdk#11]
There are too much files and if we use a large path when compiling we can get that fail
there are 10308 .o files in build/libPs4Kern
We need to fix that

**Comment by hitodama** [comment]
Uh, thanks! Did not consider that. Hmm, I will come up with something.

This is at archive time right? *.o => .a The string gets too large for the shell?

**Comment by psxdev** [comment]
yes in my freebsd vm i need to generate .a by hand my path is high in size

**Comment by hitodama** [comment]
Hmm, I dont have a good idea yet how to do this, but I am sure it will work somehow. At worst I need to add them in a loop in small chunks or one by one ^^'

**Comment by psxdev** [comment]
osx has the same issue. Looking a better method to avoid build libPs4Kern_stub.a manually

**Comment by hitodama** [comment]
It would be very cool if you come up with something :)!!

**Comment by unknownv2** [comment]
I also get this error on a FreeBSD vm and OSX. @hitodama what OS do you use to build ps4sdk?

**Comment by hitodama** [comment]
I build under Linux. I will target this issue now, since its a relevant and use-blocking issue :) I will commit a fix asap, after i figure out how to best tackle this.

**Comment by hitodama** [comment]
I hope https://github.com/ps4dev/ps4sdk/commit/da2f38d57a346f43b9a0d4136505f737055b5cf4 fixes the issue :)
As I don't suffer from the same limitation, I would appreciate if you report back.

**Comment by psxdev** [comment]
fail in osx with:
ar  rcs /usr/local/ps4dev/git/ps4sdk/core/../lib/libPs4Kern_stub.a /usr/local/ps4dev/git/ps4sdk/core/../build/libPs4Kern/*
/bin/sh: /usr/local/ps4dev/host-osx/x86_64-pc-freebsd9/bin/ar: Argument list too long
make[1]: **\* [/usr/local/ps4dev/git/ps4sdk/core/../lib/libPs4Kern_stub.a] Error 126
make: **\* [all] Error 2

**Comment by hitodama** [comment]
Hmmm, I was half expecting this.
The other (simple) approach which I expect to work is **very** slow thou ...
Essentially, it adds one object file at a time to the archive (which recreates the archive over and over each time). Since there are a lot, this is not a good approach (but I bet it would work).

Hmm ... :( I will write a (dirty) fix around this (an external program/script probably) and commit it tomorrow. Just so that this is no longer such a bad issue for now, and i can focus on other things.

**Comment by psxdev** [comment]
For directories with many object files we could do something like:

xargs ar rcs /usr/local/ps4dev/git/ps4sdk/lib/libPs4Kern_stub.a < /tmp/list.txt

instead of ar  /usr/local/ps4dev/git/ps4sdk/lib/libPs4Kern_stub.a rcs with_insane_long_line_with_object_files

where list.txt is an ls ouput from directory containing .o files.

generating split list would be a pain in the ass

it's weird, 
ls gives correct ouput so ls > /tmp/list.txt has all object file in directory
ls *.o gives error -bash: /bin/ls: Argument list too long

getconf ARG_MAX
262144

That is the limit defined on osx for ARG_MAX.

**Comment by psxdev** [comment]
with my xargs approach  you will have it in seconds

**Comment by hitodama** [comment]
Agreed on the pain in the ass and the suggestion ^^ I will use an xargs script. I would prefer not to, but as you said, its best for now. :) I think i could also use a cd and the files only to reduce the path length.

The thing with ls and ls *.o is that the shell will expand \* before it is fed to ls. So \* will expand to all objects (files) and end up just as big while ls will work on the folder ^^'

**Comment by hitodama** [comment]
I assume https://github.com/ps4dev/ps4sdk/commit/0d12b2f8a42888c37232492337b46a5f37f09f1b resolves this for now :)
Thanks for the feedback and suggestion.

**Comment by fx0day** [comment]
Thx it's fixed for me :)
