### ISSUE TITLE
linker options changed from last commits

### ISSUE THREAD

**Issue by psxdev** [ps4dev/ps4sdk#16]
before changes loader from https://github.com/psxdev/ps4link/blob/ps4sdk_work/elfldr/ps4link/Makefile compile fine only i need to add SceNet_stub in Makefile  :

clang  /usr/local/ps4dev/ps4sdk/crt0.s build/commands.c.o build/debugnet.c.o build/elfloader.c.o build/main.c.o build/ps4link.c.o build/requests.c.o -O3 -Wall -m64 -L. -Llib  -nostdlib -L/usr/local/ps4dev/ps4sdk/lib -Wl,-Ttext,0x93a300000 -Wl,-Tdata,0x93a400000 -lSceNet_stub   -lPs4_extension_kernel_execute_dynlib_prepare_dlclose -lPs4_common_mixed -lPs4_common_kern -lPs4_common_user -lPs4LibCInternalMixed_stub -lPs4LibKernelMixed_stub -lSceLibcInternal_stub -lkernel_stub -lPs4Kern_stub -lPs4_base_stub_resolve_minimal -lPs4_base_kern_dlsym_standard -lPs4_base_kern_seek_elf_address_standard -lPs4_base_assembler_syscall_rop_0x93a4FFFF8 -lPs4_base_assembler_register_standard -o bin/ldr
objcopy bin/ldr -O binary bin/ldr

however with new changes default libraries are not added by default:
clang   /usr/local/ps4dev/ps4sdk/crt0.s build/commands.c.o build/debugnet.c.o build/elfloader.c.o build/main.c.o build/ps4link.c.o build/requests.c.o -O3 -Wall -m64 -L. -Llib  -nostdlib -L/usr/local/ps4dev/ps4sdk/lib -Wl,-Ttext,0x93a300000 -Wl,-Tdata,0x93a400000 -lSceNet_stub   -o bin/ldr

**Comment by psxdev** [comment]
ps4_bin.mk
includes now freestanding.mk , ps4.mk and all_and_clean.mk

You changed ps4_untargeted.mk now it is not including default libraries

Which must be default behaviour for ps4_bin to avoid adding all default libraries by hand?

**Comment by hitodama** [comment]
Hmm, oh sorry, I forgot about bin as I was concerned with elf. I would have noticed it today later (working on the elf loader). I will fix it to be "default" behaviour just as usual.

**Comment by hitodama** [comment]
https://github.com/ps4dev/ps4sdk/commit/001bfa5f269dd5d0b78f935758fb1da99a3161eb should restore the behaviour. Will test it later while working on the loader.
