### ISSUE TITLE
Missing header file "opt_compat.h"

### ISSUE THREAD

**Issue by unknownv2** [ps4dev/ps4sdk#18]
include/machine/reg.h:41:10: fatal error: 
      'opt_compat.h' file not found
# include "opt_compat.h"

Works fine once you add an empty header (opt_compat.h) in the include dir. Error occurs when you include sys/ptrace.h in a kernel 'module' (kmain.c).

**Comment by hitodama** [comment]
Hi! Thanks, I look into it and resolve it :)

**Comment by hitodama** [comment]
I looked into it. The best approach seems to be, to define _STANDALONE. I should add such things to a standard header, like kern.h. But I will also add an empty file as you suggested, since the real file seems obscure. Thanks again :)

**Comment by hitodama** [comment]
Resolved with https://github.com/ps4dev/ps4sdk/commit/53924989bf289079047dd7dcf134ca061d98cfb8
